theme: jekyll-theme-cayman
title: LEAK Leeks
description: FA18 ECE3400's premier team 5
logo: /images/LeekColor.svg

github:
  repository_url: https://github.com/liampatterson/FA18-ECE3400

header_pages:
    - aboutus.md
